#pragma once

#if CONFIG_LCD_BOARD_SENSECAP_INDICATOR_WXM
#define D1L_TARGET_NAME "weatherxm_wg1200"
#define D1L_MANUFACTURER "WeatherXM AG"
#define D1L_PRODUCT_NAME "WG1200 / D1 Gateway"
#define D1L_FIRMWARE_NAME "WeatherXM WG1200 DeskOS"
#define D1L_USB_CONSOLE_PROMPT "wg1200> "
#else
#define D1L_TARGET_NAME "seeed_indicator_d1l"
#define D1L_MANUFACTURER "Seeed Studio"
#define D1L_PRODUCT_NAME "SenseCAP Indicator D1L"
#define D1L_FIRMWARE_NAME "MeshCore DeskOS D1L"
#define D1L_USB_CONSOLE_PROMPT "d1l> "
#endif
#define D1L_FIRMWARE_VERSION "1.8.0"
#define D1L_CONSOLE_SCHEMA 1

#define D1L_DISPLAY_WIDTH 480
#define D1L_DISPLAY_HEIGHT 480

/* Europe (EU868) MeshCore Default - 869.618 MHz / 62.5 kHz / SF8 / CR8 (4/8) */
#define D1L_RADIO_EU_REGION_LABEL "Europe"
#define D1L_RADIO_EU_PROFILE_ID "eu868-meshcore-default"
#define D1L_RADIO_EU_FREQ_HZ 869618000ULL
#define D1L_RADIO_EU_FREQ_MHZ 869.618f
#define D1L_RADIO_EU_BW_KHZ 62.5f
#define D1L_RADIO_EU_SF 8
#define D1L_RADIO_EU_CR 8
#define D1L_RADIO_EU_TX_POWER_DBM 22

/* Canada/USA (US915) MeshCore Default - 910.525 MHz / 62.5 kHz / SF7 / CR5 (4/5) */
#define D1L_RADIO_USCAN_REGION_LABEL "Canada/USA"
#define D1L_RADIO_USCAN_PROFILE_ID "uscan-meshcore-default"
#define D1L_RADIO_USCAN_FREQ_HZ 910525000ULL
#define D1L_RADIO_USCAN_FREQ_MHZ 910.525f
#define D1L_RADIO_USCAN_BW_KHZ 62.5f
#define D1L_RADIO_USCAN_SF 7
#define D1L_RADIO_USCAN_CR 5
#define D1L_RADIO_USCAN_TX_POWER_DBM 20

/* Default active preset: Europe */
#define D1L_RADIO_REGION_LABEL D1L_RADIO_EU_REGION_LABEL
#define D1L_RADIO_PROFILE_ID D1L_RADIO_EU_PROFILE_ID
#define D1L_RADIO_FREQ_HZ D1L_RADIO_EU_FREQ_HZ
#define D1L_RADIO_FREQ_MHZ D1L_RADIO_EU_FREQ_MHZ
#define D1L_RADIO_BW_KHZ D1L_RADIO_EU_BW_KHZ
#define D1L_RADIO_SF D1L_RADIO_EU_SF
#define D1L_RADIO_CR D1L_RADIO_EU_CR
#define D1L_RADIO_TX_POWER_DBM D1L_RADIO_EU_TX_POWER_DBM
#define D1L_RADIO_TCXO "NONE"
